name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image and Publish
      run: |
          docker build . --file Dockerfile --tag docker.pkg.github.com/plopix/docker-varnish6/varnish6:latest
          docker login docker.pkg.github.com --username plopix -p ${{ secrets.GITHUB_TOKEN }}
          docker push docker.pkg.github.com/plopix/docker-varnish6/varnish6:latest
